language: android

android:
  components:
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build check

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
